language: python

python:
  - "2.7"

install: "pip install nose coverage"

script: nosetests --cover-erase --with-coverage --cover-package=cleanslate

after_success:
  - "pip install coveralls"
  - coveralls
